package com.example.mynotes.settings

import androidx.compose.runtime.Immutable

/** Persisted UI, feedback, layout and performance preferences. */
@Immutable
data class AppSettings(
    val configurationMode: String = "unset",
    val darkMode: Boolean = false,
    val backgroundColor: String = "neutral",
    val backgroundToneIndex: Int = 0,
    val backgroundIntensity: Float = 0f,
    val settingsPanelTone: Float = 0f,
    val surfacePanelIntensity: Float = 72f,
    val headerIntensity: Float = 18f,
    val textColor: String = "auto",
    val textOutlineEnabled: Boolean = false,
    val sliderStyle: String = "capsule",
    val font: String = FontPreferencePolicy.SYSTEM_DEFAULT,
    val fontSize: Float = 16f,
    val soundEffectsEnabled: Boolean = true,
    val soundEffectsVolume: Float = 65f,
    val soundEffectsTheme: String = "classic",
    val reminderSoundEnabled: Boolean = true,
    val reminderSoundVolume: Float = 65f,
    val reminderRingtone: String = "classic",
    val hapticEffectsEnabled: Boolean = true,
    val hapticEffectsIntensity: Float = 55f,
    val hapticEffectsStyle: String = "soft",
    val language: String = "system",
    val gridColumns: Int = 2,
    val sortOrder: String = "newest",
    val profileImageUri: String = "",
    val profileImageSize: Float = 46f,
    val iconStyle: String = "rounded",
    val iconSize: Float = 22f,
    val accentColor: String = "palette",
    val noteCardCornerRadius: Float = 18f,
    val noteCardElevation: Float = 1.5f,
    val noteCardPadding: Float = 12f,
    val noteCardImageHeight: Float = 112f,
    val noteCardOutlineEnabled: Boolean = false,
    val noteCardOutlineWidth: Float = 0f,
    val noteTitleMaxLines: Int = 4,
    val noteContentMaxLines: Int = 6,
    val noteLineSpacing: Float = 1.20f,
    val showNoteDate: Boolean = true,
    val showCategoryChip: Boolean = true,
    val showFavoriteIcon: Boolean = true,
    val fabSize: Float = 58f,
    val optionMenuOrder: String = "edit,favorite,pin,priority,color,move,delete",
    val optionMenuHiddenItems: String = "",
    val optionMenuShowIcons: Boolean = true,
    val optionMenuTextColor: String = "note",
    val optionMenuOpacity: Float = 100f,
    val priorityMenuHiddenItems: String = "",
    val colorMenuHiddenItems: String = "",
    val performanceMode: String = "balanced",
    val animationsEnabled: Boolean = true,
    val animationStyle: String = "zoom",
    val animationEasing: String = "standard",
    val animationSpeed: Float = 1f,
    val animationIntensity: Float = 1f
)
